### ISSUE TITLE
Rename shared TypeScript interfaces for clarity

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#108]
In #99, I introduced `src/interfaces/DataViewerProposal.ts` as a named and shared TypeScript interface. I used the `DataViewer` prefix to distinguish it from the existing `Proposal` interface that represents the proposal as modeled by the API.

@jasonaowen [pointed out](https://github.com/PhilanthropyDataCommons/data-viewer/pull/99#pullrequestreview-1414029214) that this is inverted, and we should rename `Proposal` to `ApiProposal` (and do the same for other API-specific interfaces), and let `DataViewerProposal` (and other first-party, local-to-this-project interfaces) go prefixless.

For expedience and to reduce conflicts with other branches, I marched onward with the merge but we should make this change ASAP.

**Comment by reefdog** [comment]
#110 renames the API-modeled interfaces, but we still need to determine a good name for `DataViewerProposal`. This is the simplified shape of a single version of a proposal ([the most recent version](https://github.com/PhilanthropyDataCommons/data-viewer/blob/6e1f242dec0bc3fba096786fc5f98ffc00d5853b/src/map-proposals.ts#L15)):

```json
{
  "id": "248",
  "values": {
    "organization_name": ["ABC 123"],
    "board_of_directors": ["John Smith", "Jane Doe"]
  }
}
```

So here we have:
- ID of this proposal
- The shortCode for each field (as the `values` key)
- An array of values for that field (since multiple values can be assigned to a single field)

We aren't capturing:
- Explicit `position` order
- Multiple versions

We currently only use this to compose proposal list views (tables, grids) where we don't need deep version information.

Semantically, what I think this name needs to communicate
- This data has been prepared/shaped for a certain purpose
   - Do we embed this purpose into the name? Or have a generic name like `Processed`? I lean former.
- This is only a single version of data

**Comment by jasonaowen** [comment]
Excellent summary, @reefdog!

I like the idea of encoding into the name that this is for a particular purpose. Maybe something like `ProposalListItem`? If so, perhaps it would be worthwhile to also rename `<ProposalListGridItem>` to avoid confusion - maybe `<ProposalListGridCell>` or `<ProposalListGridRow>`?

**Comment by reefdog** [comment]
> I like the idea of encoding into the name that this is for a particular purpose. Maybe something like `ProposalListItem`? If so, perhaps it would be worthwhile to also rename `<ProposalListGridItem>` to avoid confusion - maybe `<ProposalListGridCell>` or `<ProposalListGridRow>`?

The correct name for grid elements are "container" and "item", though "parent" and "child" are also used conversationally. I don't really want to lose that terminology in pursuit of this goal, so I'd prefer to keep `ProposalListGridItem`.

For the interface, what do you think about `ProposalListSummary`? In a way, that's what it is… a "summarized" version of the proposal. (Latest version, flattened, etc.) I can keep thinking…

**Comment by reefdog** [comment]
I'm going to close this issue. The interface in question is now called `FrontEndProposal`, and I think that will do until we need to do more with it, at which point I think a better name will present itself.
