### ISSUE TITLE
What level of authorization is initially needed?

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#3]
For the initial version of the project — that is, setting aside long-term vision — do we need to gate the viewer website? If so, what level of authorization and authentication do we need?

In increasing levels of complexity:

1. Public, no gating.
2. Password gate using **HTTP Basic Auth** and a single shared password. Worst UX since the user can't see anything before being prompted to enter a password, but easy to do (assuming our deployment platform supports it).
3. Password gate using **our own authorization** and a single shared password. No real improvement security-wise over ②, but better UX since we can control the layout/language of the password entry page. (Example: [Vimeo private videos](https://vimeo.com/186298850).) While password-gating is substantially simpler than true accounts, it still comes with the overhead of picking an authorization library and integrating it into our app, versus basic auth which the app itself doesn't need to know about.
4. Actual accounts (whether shared or not) using individual usernames/passwords. This is a big leap from ③ and involves actually identifying individual accounts and all the overhead that comes with that (account management, registration, datastore, etc.).

cc @jim-mcgowan @slifty (and anyone else) to discuss.

**Comment by bickelj** [comment]
This is both a response to the question and a follow-up to my comment on the other issue at https://github.com/PhilanthropyDataCommons/data-viewer/issues/4#issuecomment-1332405746.

If we don't agree on an Authorization Server soon and keep the pre-shared API keys, I think (3) with the front-end UI entry simply "paste your pre-shared API key" and the UI passing it through to the back-end service.

I think (4) is possible with keycloak where yes, we have the overhead of all that, but we also have a widely-used tool that is tailor-made for this purpose and implements some common protocols for authentication and authorization.

**Comment by jim-mcgowan** [comment]
@reefdog: This will be decided at a meeting of the PDC Pilot Leadership Team on Tuesday, December 13. While I appreciate all the technical considerations, this is really about who should get to see the PDC-collected data.

**Comment by jim-mcgowan** [comment]
@reefdog: We can use Friday's meeting to determine what options we want to present.

**Comment by slifty** [comment]
I would encourage us to plan for ultimately supporting 4 (note: supporting doesn't mean implementing, just making sure the implementations we do have the future of 4 in mind / we're doing things well), but implementing something lighter weight based on the outcome of that December 13th meeting.

**Comment by reefdog** [comment]
We're going to assume we need to implement ④ and move forward with that.

Bookmarking to explore:
- [Auth.js + SvelteKit](https://authjs.dev/reference/sveltekit/modules/main)
- [Auth.js's documentation on Keycloak as a provider](https://authjs.dev/reference/oauth-providers/keycloak)
