### ISSUE TITLE
Choose new name for Data Viewer

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#315]
The Data Viewer (project and application) is destined to allow data entry. Consequently, the name "Data Viewer" is not a fitting name. Either we need a read/write-focused name, or, this can be canonically referred to as something like "the front end" or "the PDC".

**Comment by slifty** [comment]
Here's a Really Good Brainstormed List:

* Data Viewer, Bath, and Beyond
* Data Portal
* PDC Portal
* Data Viewer
* Data Hub / PDC Data Hub
* Data Viewdeditor
* Data Catalogue
* Data Catalog
* Data Cadalok
* Data Vuvuzeladlock
* Apple Inc.

I think I vote for PDC Portal

**Comment by kfogel** [comment]
I think "PDC Portal" is fine (w/ `data-portal` as repository name).

I suspect that colloquially sometimes it will be referred to as the "PDC Data Portal" and sometimes as "the Portal", and we should just roll with that if so.

Let's just start using "PDC Portal" in writing, and any of the above in speech.  Meanwhile, Jim and I can mention it to the rest of the team and see if they have any strong opinions.

Okay to close this?

**Comment by slifty** [comment]
*sigh* I'm instantly regretting not highlighting `Data Viewdeditor`

**Comment by slifty** [comment]
UPDATE: others wanna weigh in so let's allow space for that!

**Comment by jasonaowen** [comment]
Thanks for raising this, @reefdog! I feel like we've said it out loud a few times, but I appreciate you writing it in an issue. And thank you @slifty for starting the brainstorming process!

I feel like "portal" doesn't convey any useful information - it does not describe the repo, and if I were an outsider I don't think seeing a repo named "portal" would tell me much about its contents. (See also: [GitHub repo search for "portal"](https://github.com/search?q=portal&ref=cmdform&type=repositories), which contains a wide variety of projects.)

Likewise, including "data" in the name doesn't add much in the context of the "Philanthropy Data Commons".

(Separately, I'd prefer if the repo name did not share a prefix with any other repos in this org, as it makes command line tab-completion less convenient. That might mean we should rename `data-scripts` if we want this repo to be `data-something`.)

`front-end` seems like the most descriptive name so far, although it's also the most boring. I'm open to other ideas!

**Comment by kfogel** [comment]
(Happy to continue thinking/discussing.)

It might make sense to rename the repository to `front-end` right now, and accept that the public-facing name may take a while to decide and/or change in the future.  I.e., let's decouple these two things, so that the PDC's evolving messaging requirements don't cause us needless dev churn.

**Comment by jasonaowen** [comment]
@kfogel I'm confused - can you say more about what two things you propose to decouple? Also, you seem to be acting with a sense of urgency; am I reading that correctly, and if so, can you say why?

**Comment by slifty** [comment]
My only hesitation is that it's also pretty generic (pretty much as generic as `portal`). I agree `portal` alone is general.  I don't really agree that `data-portal` adds no context.  The interface is genuinely a data portal, that's what it is!

For instance: It's not a documentation portal, or a user administration portal.

All of that being said, I don't have super strong feelings.

---

I do agree with Karl that the product name wouldn't end up being "PDC Front End" -- and actually it might be nice to have the repository named so blandly that we won't have to consider changing it as the user-facing branding evolves.

**Comment by bickelj** [comment]
I am OK with any of these and probably others too:
- `data-portal`
- `portal`
- `gui`
- `front-end`

**Comment by reefdog** [comment]
Current copy atop https://pilot.philanthropydatacommons.org/:

> **Welcome to the Philanthropy Data Commons pilot.**
> 
> This data viewer displays the data in the Philanthropy Data Commons pilot. [Read more about the project here.](https://philanthropydatacommons.org/)

We have three names going on here:
- Philanthropy Data Commons
- pilot
- data viewer

This task is about **renaming the `data-viewer` repo** (and how we discuss it internally), but **informed by** the name people naturally use to describe the website where they interact with the PDC (and which is served by this repo). Those two things don't need to be tightly coupled, and @jasonaowen I believe that's the decoupling @kfogel is proposing.

Thoughts:
- I suspect people will interchangeably use the term "the PDC" to refer both to the data itself (as provided by the `service`) and the website that they log into (as provided by the `data-viewer`), based on context. E.g., "Is our proposal in the PDC?" vs. "When was the last time you logged into the PDC?"
- I think this repo will always be served on a subdomain; `www.philanthropydatacommons.org` will be a separate marketing site, while this site will be available at e.g. `app.philanthropydatacommons.org` (and the API at `api.philanthropydatacommons.org`). Thus, assuming one day we have a repo for the marketing site, they should be easily distinguishable by name.

--------

I have to go pick up kids from school so will send now and catch up later. But I'm leaning toward `gui` or `front-end`.

**Comment by jasonaowen** [comment]
> This task is about **renaming the `data-viewer` repo** (and how we discuss it internally), but **informed by** the name people naturally use to describe the website where they interact with the PDC (and which is served by this repo). Those two things don't need to be tightly coupled, and @jasonaowen I believe that's the decoupling @kfogel is proposing.

Aha! That makes sense, thank you for helping me understand. +1 to decoupling those things!

**Comment by reefdog** [comment]
I do think of this as the portal to the PDC, and I do like the name `portal`. (Yes, the API is also a portal. But it already has a great name: "the API"!) That said, to @jasonaowen's point, `portal` is ambiguous and a little weird, while `front-end` is clear and well-understood by all of us. I do also like `gui`, but `front-end` feels a bit more web-native.

**Comment by slifty** [comment]
I think `front-end` has some consensus vibes going on!

**Comment by reefdog** [comment]
> Though maybe we should reconsider `data-viewer-bath-and-beyond`

We can email users 20% off token size coupons every few weeks. And they never expire!

**Comment by bickelj** [comment]
@reefdog I got it. And I recall trying to find the most recent 20% off coupon when I finally needed to go to BB&B but not finding it!

I also got this email this morning from the "new" BB&B aka Overstock:
> Get 15% off When You Shop 🍂 All Things Fall 🍂

**Comment by reefdog** [comment]
@bickelj Apparently I was trolled and the “friend” who didn’t get it just wanted me to feel bad and exclusive. The authorities have been informed.

**Comment by slifty** [comment]
I don't get it.

**Comment by reefdog** [comment]
It sounds to me like we have consensus around `front-end`. Could I get a show of emoji hands from anyone who sees this notification?

**Comment by jmergy** [comment]
portal or front-end is fine with me.

**Comment by jasonaowen** [comment]
The repo bike shed has now been painted! Let the discussion of colors for user-facing naming bike shed commence. (That is, the repo has been renamed; let's decide on what to call the application on the website and so on.)

**Comment by slifty** [comment]
In the spirit of bike shedding, and since I think everybody has vocalized opinions, I vote we fully empower @reefdog (and @jim-mcgowan!) to make this call

**Comment by reefdog** [comment]
And in the further spirit of "it's easier to critique suggestions than blue-sky", I'm going to open a PR with user-facing suggestions so that everyone (but especially @jim-mcgowan) can comment on specific context examples.

**Comment by reefdog** [comment]
@slifty @jasonaowen @kfogel @jmergy I didn't tag y'all as reviewers on #332, just @jim-mcgowan, but please feel free to optionally weight in regardless!

**Comment by kfogel** [comment]
I'll comment on @reefdog's new PR once it's filed.

**Comment by reefdog** [comment]
@kfogel Here you go! https://github.com/PhilanthropyDataCommons/front-end/pull/332

**Comment by jim-mcgowan** [comment]
@reefdog Is there a reason we're not calling it the **Data Commons**? cc: @kfogel

**Comment by reefdog** [comment]
@jim-mcgowan We are! I mean, unless you're proposing "PDC Data Commons", which I would argue is redundant.

What we're basically debating is what term we use in the "welcome" text on the landing page (and the window title, which you can see most of in the browser tab):

<img width="912" alt="landing-page" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/960aac83-61b9-4e62-b860-81aed3f793a4">

In #332, I went with just "Philanthropy Data Commons". I kept the word "pilot" but only because I'm not sure if we are now out of the pilot phase or not; if so, great, I'll remove that word and it will read "Welcome to the Philanthropy Data Commons".

We've debated whether we need an additional noun, e.g. "Welcome to the Philanthropy Data Commons Portal". But I would argue that people aren't thinking of "the PDC", "the PDC service (and its API)", and "that website where we view data in the PDC" as separate things. Sure, one is "the entire project", one is "the actual data store and API", and one is a web-based client of the data store; but that's as functionally immaterial as clarifying "Amazon the corporate entity" from "Amazon the e-commerce website". You can just say "Amazon" and context clears it up.

Does that all make sense / sound sound?

**Comment by reefdog** [comment]
@jim-mcgowan Great! Am I correct in keeping the word "pilot" for now, too?
