### ISSUE TITLE
Move hosting to PDC-owned Netlify account

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#339]
The front-end is hosted at Netlify by @jasonaowen's OTS account. We should instead have some sort of organization/corporate account and provide access to devs as needed.

I think Netlify makes this annoyingly expensive, e.g. by charging for each user with access, but it's still worthwhile to ensure no individual developer — no matter how trusted and beloved — has the exclusive keys.

**Comment by reefdog** [comment]
I'm assigning this task to @kfogel and @jasonaowen, but I assume @kfogel will triage it to the correct systems person.

**Comment by jmergy** [comment]
Agree - we can provision an account off MacFound

**Comment by kfogel** [comment]
@jmergy Do we have the ability to have MacFound provision this and give us the keys?  If not, then we should create one owned by OTS.

Either way, the creds will live in `opass`, and @smpsnr will know how to put them in there.

**Comment by reefdog** [comment]
@jmergy I'm going to assign this issue to you to get the ball rolling. Feel free to reassign as needed, and unassign yourself once you've been able to provision the account and handed off the keys.

**Comment by jmergy** [comment]
@reefdog @kfogel taking this now and will update when we have an account ready to go for the transfer

**Comment by reefdog** [comment]
@jmergy Any update from MacFound on this?

**Comment by jmergy** [comment]
They are aware and waiting for me. I'll email.

**Comment by jmergy** [comment]
@reefdog I have a new account. Coordinating on payment now. Which address/user would we want for OTS?

**Comment by reefdog** [comment]
@jmergy The OTS user should be Jason (`jasonaowen@opentechstrategies.com`).

This is presuming that:
1. You/MacFound "own" the account and so it can outlive any shuffling of the development team, and
2. Jason is an additional developer (so you can always revoke / reassign his access to someone else), and
3. It's not best practices (and maybe against Netlify TOCs) for us to have a "group account" like `netlify@opentechstrategies.com`

**Comment by jmergy** [comment]
Great thanks @reefdog - that Jason has been invited and can proceed with the transfer once establishing membership in that new PDC-managed account.

**Comment by reefdog** [comment]
@jmergy Thank you! I think Jason can manage the rest of the migration, now that he has access. I'll reassign this task to him, and then he can close once migrated. Appreciate all the help!

**Comment by reefdog** [comment]
Huzzah!
