### ISSUE TITLE
Create bulk upload route and page

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#409]
We need an "Add Data" page that currently defaults to a bulk uploader in the sidebar and instructional copy in the main pane:

![Upload CSV](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/da448919-e554-4a77-9c95-22cc2c2c938c)

This will use a [Panel Grid Plus Sidebar](https://pilot.philanthropydatacommons.org/storybook/?path=/story/stories-panelgrid--plus-sidebar).

Suggestions welcome for the path. This is easily changeable in the future and shouldn't tie us up. I recommend a simple `/add-data`.

**Comment by jmergy** [comment]
Like the sidebar use

**Comment by reefdog** [comment]
This has been done!
