### ISSUE TITLE
Create file-upload component

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#411]
As described in #365, we want a file-upload component with the following states:

| State | Appearance | Notes |
| ----- | ---------- | ----- |
| Idle | ![Idle](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/b5751131-855b-4973-b8ca-dfc2cc354ee8) | User can drop a file or click to load system uploader. |
| Waiting |  ![Waiting](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/22106647-27a0-4775-a4d8-3289389252d0) | When user is holding a file over the drop target. |
| Uploading | ![Uploading](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/1f37b5e9-d25f-41dd-8d64-299c0a24055c) | Animated spinner (no actual "progress" unless it's effectively free). |
| Uploaded | ![Uploaded](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/edd385f5-cd5f-479e-9c62-9f597060ff82) | Appears temporarily (5–10s?) after upload is complete and processing has begun. It's okay if the user misses this a "Processing…" item will have been added to the history below at the same time. |
| Pre-flight Error | ![Error](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/04a6e85b-c188-4542-9656-74a42b057a76) | Displays when the file upload (not processing) throws an error. Uploader is still a drop target for new files, but "Reset uploader" (or whatever language we use) is an explicit path to "Idle" state. |

For the purposes of this issue, we only need to represent these states in the component and define the surface area for manipulating them and customizing language. A separate issue will actually tie in the upload actions, callbacks, etc.

**Comment by jmergy** [comment]
Looking great.

**Comment by jasonaowen** [comment]
My initial research found [react-dropzone](https://react-dropzone.js.org/), which looks promising; I haven't used it before, but it seems to be the most popular by far. It's fairly low-level, though, and in its documentation points to [filepond](https://pqina.nl/filepond/). I'll need to look into these more!

@reefdog if you have recommendations or past experience, I'd be interested to hear! No worries if not.

**Comment by reefdog** [comment]
@jasonaowen I began building it yesterday and — while I hope I don't regret this decision — it seems fairly easy to achieve on our own natively. [This guide](https://www.codemzy.com/blog/react-drag-drop-file-upload) (which I referenced but am not copying) using vanilla React shows just how simple it can be.

But that's a good find and I'll keep it as a parachute.
