### ISSUE TITLE
Write instructional copy for bulk upload

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#416]
The "add data" page will need instructional copy to guide users. I wrote some quick filler copy for the design ([see mockup](https://github.com/PhilanthropyDataCommons/front-end/issues/365#issuecomment-1817268373)), but this issue is for writing it For Real, and then getting sign-off from the appropriate stakeholder/s.

Assigned to myself to take the first pass, but greedy reassignment welcome.

**Comment by reefdog** [comment]
I've added the initial copy to the wiki: https://github.com/PhilanthropyDataCommons/front-end/wiki/Bulk-Upload-%E2%80%90-Instructional-Copy

Passing it off to the team to further refine. Once you're happy, you can close this issue and mark #417 as ready to work on.

**Comment by reefdog** [comment]
BTW, if we're worried about the instructional copy pushing the base fields down too far, I had an idea for how to condense it a little using expandable sections:

<img width="1512" alt="Proposals - Upload CSV" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/7a9d0d40-f645-4848-a1bf-ad4fcbd7dc25">

However, this would be reserved for an improvement later.

**Comment by jasonaowen** [comment]
> To use the API, request an API key from `team@philanthropydatacommons.org`

We're using `info@` for the feedback navbar button and landing page call to action; should we also use that email address here or are these different addresses for different purposes? @reefdog or @jim-mcgowan?

**Comment by reefdog** [comment]
…huh, I'm not sure why I used that one. I remember doing so intentionally, but I can't find any reference to `team@` in the obvious places, so it may have just been an error!

In any case, yes, let's make sure to change that to the actual email address people should email for an API key. 😆

**Comment by slifty** [comment]
This is marked as completed on our project board so I *think* this is completed in general?  please re-open if I'm incorrectly closing.
