### ISSUE TITLE
Add bulk upload instructional copy and link CSV template

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#417]
Once instructional copy has been approved (#416), populate the interface with it! This will also include a local link to the CSV template, which I _assume_ will be a statically-hosted copy of the [service repo's canonical version](https://github.com/PhilanthropyDataCommons/service/blob/main/src/public/bulkUpload.csv). (If we can point directly to that one… even better, maybe?)

**Comment by slifty** [comment]
Neato!

https://api.philanthropydatacommons.org/static/bulkUpload.csv

**Comment by reefdog** [comment]
To be more explicit: the front end can — and should! — hotlink to the API-provided bulk upload template that Dan linked above.
