### ISSUE TITLE
Show data source

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/front-end#45]
Once https://github.com/PhilanthropyDataCommons/service/issues/116 is resolved, display that data in the UI.

In this example, the "Brighter Future Foundation" is the data source:

<img width="434" alt="organization name, EIN, and data source" src="https://user-images.githubusercontent.com/1494855/228952557-2e6179a7-83a6-489d-b614-7df33a29acab.png">

The designs have this in the proposal detail panel, below the proposal title, and to the right of the organization name.

**Comment by reefdog** [comment]
We've discussed it a few difference places but evidently not here!

My intention with that element was to communicate to the user — currently all PDC stakeholders — "where did this particular proposal come from?" I thought that would be an easy question, but evidently it's not! There are technical data sources ("a GMS imported it via the API…") and conceptual sources ("…on behalf of their client, the foundation which runs the opportunity to which the proposal was responding") and then gray in between.

Before we worry about where this data comes from and how to express it, we need to re-state what questions the user is asking that the UI element is trying to answer. Basically, we need a user story here.

I expect we'll actually end up with multiple concepts here, and need to split "data source" into multiple tags for each purpose.

**Comment by slifty** [comment]
Good news everyone!  Provenance is officially part of Phase 3.

That said, it isn't clear if there is going to be a UX implementation to show the provenance.  For now I'll move this to the Phase project 3 though

**Comment by reefdog** [comment]
If we _do_ decide to show provenance in the UI, I'll want to take another pass at it, with a better understanding of what sort of provenance we're tracking and what questions the user wants answered. My original design implementation was naive.
