### ISSUE TITLE
Design UX for error reporting

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#477]
When a bulk upload fails, users need to be told why it failed and how to resolve it.

The API will provide errors at the individual cell level. That is, which **row** (entity/proposal) and which **column in that row** (field), along with a description of the error. For MVP, we won't give the user any inline capability of resolving the error. They will have to fix the CSV and try the upload again.

**Comment by reefdog** [comment]
Here's my first pass at the UX. This will require a "detail page" for individual bulk uploads. This is necessary for error reporting because we could need substantial amounts of space, if there are many problematic rows and fields.

1. Users click on a bulk upload in the sidebar history
2. A new panel appears between the upload sidebar and the instructions
3. This panel contains metadata about the upload, as well as error detail below the metadata. This could either be a detailed field-level error table (as shown in the big screenshot below) or a simple error message when the file fails a preflight check (see the variation directly below the big screenshot).

Note that the language here assumes a transactional upload in which any error blocks all rows from being imported. If this isn't the case, then we will need two error variants: one in which the upload failed before any data was imported, and one in which data was partially imported.

**Full interface, with field-level error report:**

<img width="1512" alt="Proposals - Upload CSV - Failed" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/76055d82-68a2-47ff-852f-a4063af052b2">

**Non-field-level error report:**

<img width="447" alt="Proposals - Upload CSV - Failed Preflight" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/6e09f538-fa46-47c8-a88a-4590323f2c7e">

As long as we're building this, we can go ahead and build a detail page for successful bulk uploads as well. In the future this can contain a table of all the proposals that were imported from the file, but MVP will not include this table. (I put it on the mockup to demonstrate this.)

<img width="1512" alt="Proposals - Upload CSV - Succeeded" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/b606eddb-c427-41b6-9f4b-f859540845ea">

**Comment by reefdog** [comment]
@jasonaowen @slifty What do you think about the above?

**Comment by reefdog** [comment]
### Long discourse on the slight weirdness of this panel layout

I want to recognize something a bit weird here: The detail panel opens _between_ the index sidebar and the instruction panel.

Prior to this, the only place we use a three-panel layout is on the proposal detail page. There, we treat each successive panel (from left to right) as adding detail: first panel is the index, next panel is the entity, and last panel is a (closable) child of that entity.

We will re-use that grammar for other hierarchical entities, e.g. once we have true applicant pages. You can imagine a sidebar of applicants; a main panel with the selected applicant's details; and then an (optional/closable) third panel with some child/relation of the applicant that the user has selected, like perhaps proposal detail.

This design contradicts that left-to-right panel hierarchy. Here, we have a multi-purpose sidebar (it's both a file upload UI and an index of bulk upload history), with a main panel full of static instructions. Clicking on a bulk upload opens the detail panel _between_ sidebar and instructions.

Conceptually, this seems to contradict the existing design language. However, I think that's only a problem when trying to _describe_ the UI. I don't think it will present an actual hiccup to users, who I think will still feel oriented. At the very least, I'd like to build it and find out!

**Comment by slifty** [comment]
These look great!  Just to confirm: your assumptions about transactionality and NOT planning to provide a downloadable CSV are both correct.

I don't know if this is going to be relevant to this issue or if it'd be something else, but there is a category of error that will result in a new "retrying" status -- for instance, inability to download the data from S3.  I'm not sure how / if you would want to signal that to the end user.

**Comment by reefdog** [comment]
Thanks @slifty!

On our call today, @jasonaowen mused that the three-panel design might not be ideal here. One, some base field names are quite long and already wrap; they'll be even worse when given half the space. Two, the instructions have limited usefulness while looking at the bulk upload detail.

So, perhaps clicking on the bulk upload history item should just take over the complete panel, which must be closed (with the X icon) to get back to the instructions?

![Field Errors](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/51dfd3aa-5244-4353-aaab-eaf3321c9e43)

![File Errors](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/4c2ea5a9-fa1f-4541-8d53-dbb7903e0701)

I don't love the lack of a positive call to action to get back the instructions, but my experimentation in the Bulk Upload sidebar haven't been satisfactory and I'm pushing my timebox. So, I think we should start here — sans instruction panel — and iterate as users provide feedback.

**Comment by reefdog** [comment]
@jim-mcgowan @jmergy @kfogel Your feedback on these designs (please scroll down to the latest) are appreciated!

**Comment by jasonaowen** [comment]
Thanks for the second pass! That's looking great to me.

> I don't love the lack of a positive call to action to get back the instructions...

Am I right in guessing that the red X in the top right corner will return to the instructions? Is it worth replacing the upload button in the top left with a "← Back", as well? Or would that cause unrelated and undesirable vertical layout changes?

**Comment by slifty** [comment]
Hmm -- realizing that the "drag and drop your CSV file here" might be misleading in the context of viewing a specific bulk upload (e.g. I might assume that interface would replace the file for the SELECTED upload rather than make a new one.)

Is this the same thing as what Jason is suggesting?

**Comment by reefdog** [comment]
Ooh, interesting. @slifty that's a fascinating assumption that I wouldn't have made but I'll bet users might, and @jasonaowen is correct that I want to avoid vertical layout jumps so just hiding/showing the uploader isn't ideal (and yes, clicking the X would go back to the instructions screen), but this gives me an idea to explore: making the uploader area of the sidebar feel more like a super-charged sidebar element that has to be "active" in order to be used, and when it's active, the documentation takes over the main panel. It would still be fully visible when inactive, but it would have to be actively "activated" before being usable again. Let me play with this!

**Comment by slifty** [comment]
@jim-mcgowan @kfogel if you have feedback on this item please drop it in here by EOB tomorrow

**Comment by reefdog** [comment]
@jim-mcgowan @kfogel @jmergy BUT wait until tomorrow morning to start that feedback… because we (@slifty @jasonaowen) discussed this interface on the after-party call and we have some ✨ improvements ✨ on the way.

**Comment by reefdog** [comment]
Okay! Based on the feedback above, this issue (UX for error reporting) has iterated into some changes to the bulk upload UX overall. That's good.

<details>
<summary>Click to optionally read the problems that these new screens are solving</summary>

We had several issues, both arising from the bulk upload detail screens (clicking on a bulk upload history item in the sidebar):

1. Once on a detail screen, the sidebar uploader kind of felt like a "upload a file to replace this upload" feature rather than a "bulk upload a new file" feature. The efficiency improvement of having the uploader present on all pages was over-shadowed by the user confusion of what the component _did_ on the history pages.
2. From the detail screen, there was no obvious "positive" path back to the instructions. One could click the [X] close button in the corner, or click the "Add Data" in the navbar. But neither were intuitive, and as evidenced by having to explain it in the initial message, our use of the [X] close button on these screens was inconsistent with how we were using it elsewhere on the site.

</details>

### Upload screen

- Uploader moved out of sidebar and replaced with link to "New bulk upload" screen
- Upload component reformatted (no longer square)
- Instructions simplified; the requirements appear to the right on larger screens, but below the drop area on narrower screens

![New bulk upload](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/d9633e42-6fc2-4b8b-8a04-4e3fb725018f)

### Detail screens

The detail panels haven't changed internally, except to lose the [X] close button. But here they are anyway for final review:

#### Bulk upload failed preflight check:

![Bulk upload failed preflight check](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/430578e5-ae3d-4c72-8271-ba322fb63586)

#### Bulk upload failed row-level errors:

![Bulk upload failed](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/1dda2892-501e-4e18-8db0-cc6c1571d9d6)

#### Bulk upload detail screen:

This is an example of a non-failure. At launch, this panel will be almost entirely blank because we don't show the processed/imported entities.

![Bulk upload succeeded](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/32283688-1baf-4e5f-a475-2dd50b581eb7)

**Comment by reefdog** [comment]
@jasonaowen Oh! And I didn't forget about your suggestion to change the icon on the uploader… I just discovered that I [already did that in the real component](https://app.philanthropydatacommons.org/storybook/?path=/docs/stories-bulkuploaderfilepicker--docs)! I just forgot to in the Figma. 😆 (But you'll also notice that I tweaked things so the navbar now uses a different icon from the sidebar element. I like this better… it differentiates the navbar icon, is a bit more future-proof, and keeps us from _over_-using that document upload icon.)

**Comment by jim-mcgowan** [comment]
@reefdog As the likely order of operations is 1. Read the requirements, 2. Download and populate the template and 3. upload the file, I would switch the text and the upload component:

<img width="1155" alt="upload" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4147733/2962d874-0182-4d84-bf4a-55fc051d0169">

**Comment by reefdog** [comment]
@jim-mcgowan Oh I definitely tried that first! As well as different variations like locking the uploader into the top-right corner of the panel. But it all felt very weird to me, like the uploader — the most important element — was being shoved off into no-man's-land.

<img width="1053" alt="Screenshot 2024-01-10 at 4 36 36 PM" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/04424ede-f0d5-4244-8c1a-0783e0e554ef">

I'm thinking of the requirements as more of an "aside" that people can start ignoring after they know them.But I'm curious what others think (and if that argument / my screenshot convince you)!

**Comment by reefdog** [comment]
@jim-mcgowan This is the closest thing to what you said that I _do_ like, submitted for your consideration and others':

<img width="1053" alt="image" src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/c8773f00-dfd5-4ace-ad70-9378fc57388e">

**Comment by jim-mcgowan** [comment]
@reefdog That's what I was thinking. Initially, everyone coming to this screen is going to be a first-timer. In addition, this window now looks more like the others (with text on the left).

**Comment by slifty** [comment]
@reefdog The new bulk upload stuff being aligned with the list of existing bulk uploads *feels* like it might be a a situation where visual hierarchy is lying to the user (e.g. the icon for upload is not the same type of element as the status icons, and the label for new bulk upload is not the same type of element as a past upload's title).

What do you think of intentionally differentiating the elements (and maybe adding a bit of white space below to separate them a little bit?)  For instance, maybe it could be a button with the icon in it so there's no expectation of alignment to external elements, and the button is centered in the space?

**Comment by slifty** [comment]
I made this -- I don't necessarily *like* it, but I made it!

![image](https://github.com/PhilanthropyDataCommons/front-end/assets/208884/9990fe9e-9510-43c6-9787-0925e5fb261f)

**Comment by reefdog** [comment]
@slifty Thanks for the note, and for the illustration! It always helps to have something to look at. 🙏 Here's the nativized version of your idea:

**Button-style, active (default):**
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/fe2a8f3b-600c-4b08-b043-f910c21386d9" alt="Bulk upload sidebar with active button-style New Upload link" width="400" />

**Button-style, inactive:**
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/cac8299a-9331-4dff-8952-97025ca129b8" alt="Bulk upload sidebar with inactive button-style New Upload link" width="400" />

I'd intentionally avoided button-like styling because (1) this is really a link and we've thus far maintained a "button == action" grammar, and (2) it's active the moment you arrive here from the navbar. For both reasons I wanted to hew more closely to our [previous standard for navigable sidebar elements](https://app.philanthropydatacommons.org/storybook/?path=/docs/stories-proposallistgridpanel--docs).

But the issue you identify is real. I do wonder if merely moving the "Bulk upload" title below the element, and renaming it to "Bulk Upload History", would do the trick? Or at least is a better place to iterate from than going all-in on a button.

**Sidebar item-style, active (default):**
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/d01dc385-df7f-4eb5-800b-f732799531cc" alt="Bulk upload sidebar with active sidebar-item-style New Upload link" width="400" />

**Sidebar item-style, inactive:**
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/44e81773-1465-4925-9cad-a5fa630b7788" alt="Bulk upload sidebar with inactive sidebar-item-style New Upload link" width="400" />

Thoughts?

**Comment by slifty** [comment]
Understood re button!

I think the new "bulk upload history" label is great and that order makes sense.

The alignment still kinda jumps out at me.

What do you think about just centering it?  Maybe adding more padding around it so it feels? 

(centered version as an example of what I mean, I didn't mess with spacing)

<img width="370" alt="image" src="https://github.com/PhilanthropyDataCommons/front-end/assets/208884/093cf533-88ea-45a0-bb48-b3da9c10418f">

**Comment by slifty** [comment]
Oh, also, what if we called it "Start new bulk upload" so it *is* an action?

**Comment by kfogel** [comment]
I've looked over these, @reefdog, and I'm sorry to say that the latest version looks good to me (if you take @slifty's suggestion to put an action verb in there).

Now, this could just be a case of my not being able to really get a feel for the UX until I use it, but from a purely visual interaction, I like it!

**Comment by reefdog** [comment]
@slifty I like that centering (sans button styling), nice! Will implement.

@slifty @kfogel I strongly disagree with adding a verb. I get that it's "Start…" and not, say, "Submit…" but it still feels like "Start…" implies an action will be performed (rather than a series of steps begun). I think it's likely to confuse first-time users especially, who will click "Add Data" in the navbar, find themselves on the upload page, and then think they have to click that link to get started (when they're actually already in the right place). If you can trust me on this one, let's start with "New…" and see it in action.

**Comment by reefdog** [comment]
We're in enough agreement with this UX direction that I'm going to call the task completed and create implementation issues. 🙏 Thank you everyone!

**Comment by kfogel** [comment]
@reefdog Yes, I can trust you on this!  +1 to closing the issue and moving ahead with the direction that we have consensus on.
