### ISSUE TITLE
Design "base field admin" interface

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#483]
We would like an admin-only interface (but open to all until we have this concept of "admin-only") for editing base field labels and descriptions.

@slifty @jasonaowen are we including the ability to add/remove new base fields?

**Comment by reefdog** [comment]
Here's my first pass at the UX for an administrative interface for editing base field descriptions. The "user" of this specific interface is… Jim. (Or any of us who want to tweak base field descriptions without writing SQL migrations.) However, we want to establish UX patterns that we would use for other inline editing interfaces, e.g. changemakers editing their organization data.

I offer three options: automatic saving, batch saving, and action required. In all of them, only one cell would be editable at a time, indicated with its thick blue outline.

#### Automatic saving

This acts like a spreadsheet. There is no save button because saves happen automatically. Users click on a cell, make their edits, and click or tab to another cell while changes are saved in the background. The escape key discards edits and blurs the cell without saving.

![Automatic saving](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/88b1e1bf-ab5e-43b1-926b-2d0e4f75036c)

#### Batch saving

This behaves largely like Automatic Saving, except changes are not saved automatically. Instead, the changed cell is highlighted, and page actions appear in the header. Nothing changes until the user takes explicit action. Discard (or page unload) with pending changes requires user confirmation.

![Image](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/dd79114e-5a9b-4ab4-a6f4-402f9bfc2d72)

#### Action required

Similar to automatic saving, except with the addition of explicit buttons to save or discard row changes. If there are no changes when the user tries to click/tab away, we allow it; if there are changes, the user is prevented from moving to another cell until they take action on this one.

![Action required](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/3453f0d3-b232-4ae6-9c98-98ced1f16050)

@slifty @jasonaowen @jim-mcgowan @kfogel @jmergy Feedback welcome!

**Comment by jasonaowen** [comment]
I think I prefer the action required workflow!

Automatic saving is nice and very modern, but I think I do want just a little bit of friction here - let's avoid any cat-walking-across-keyboard updates. Batch updating is less friction that action required, but I think it'll also require more implementation effort.

Are you intending for this interface to allow editing the short code or the label, as the API allows? Maybe a slightly-hybrid model of action required and batch updating would be good, where the "batch" is one row, but all of the fields become editable and share a single submit/cancel button?

**Comment by jmergy** [comment]
if batch - how challenging would it be to add a commit note or something like that at save? Just thinking we need to have some concept of when changes happen (and by who) especially if key or labels are changed.

**Comment by slifty** [comment]
@jmergy since this is, for now, intended as an interface that only the folks on our dev calls would use I'd suggest that is probably not a system we would want to implement at this stage.

We may want to eventually prioritize an overall user activity log, however, at which point something like that would be included.

**Comment by kfogel** [comment]
@reefdog I think the latest iteration is good as-is, FWIW.  (I also don't think we should focus too much of our attention on this interface anyway, considering how often it is used and by whom.)

**Comment by reefdog** [comment]
@kfogel There's only been one iteration of this interface so far. Are you thinking of the UX for error reporting of bulk uploads (which has been iterated to dea—health!)? Or do you mean the third of the three options above?

The justification for spending a bit of extra time on this is that we'd like to establish an editing interface here that's also appropriate for editing organization/proposal data, which will be used by a wider audience.

Dan and I are lobbying for the "batch saving" option, where a user tweaks a bunch of "cells" at once and then has to submit them all with one action. Jason has implementation concerns, among them that each row is a separate API call, and would prefer an iteration on the "action required" option. (We've all agreed the "automatic saving" option isn't appropriate.)

**Comment by slifty** [comment]
I didn't say this in the thread but will just throw out that I do think the implementation concerns are mitigable -- it's more complex, but not impossibly so, and I do think the UX byproduct is meaningfully better.

**Comment by kfogel** [comment]
I think the batch-saving approach, in which one can group multiple edits together, makes sense -- sometimes that grouping may be semantically meaningful, and we'll be glad that we had the ability to define the group via an explicit single save of multiple changes.  (And I agree with the "let's not do automatic saving" consensus.)

I don't know enough to address the implementation concerns.  Obviously, if each row is a single API call, it's easy enough to accumulate a list of changes and then iterate over that list, issuing the appropriate API call for each item in the list.  But do we have any facility in our data schema to make that set of API calls be grouped in some kind of transaction-like way?  Anyone?  Bueller?

**Comment by reefdog** [comment]
We're going to move forward with the batch saving interface. I still need to demonstrate how we will display errors to the user, but that can be an implementation task.
