### ISSUE TITLE
Explore switching from Create React App to Vite for the front-end build framework

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/front-end#498]
We're using create react app for our build system; it is no longer maintained.

Vite would be a good replacement.

**Comment by reefdog** [comment]
One consequence of being stuck on create-react-app: https://github.com/PhilanthropyDataCommons/front-end/pull/626#issuecomment-1981030769

**Comment by hminsky2002** [comment]
I shall note that simply uninstalling react-scripts, installing the vite package, and moving the index.html file to the root directory does not work. Womp womp.

**Comment by reefdog** [comment]
> I shall note that simply uninstalling react-scripts, installing the vite package, and moving the index.html file to the root directory does not work. Womp womp.

https://getyarn.io/yarn-clip/65f69bb2-1a3a-40b2-97c8-9b456c06ff82

**Comment by reefdog** [comment]
We can call this task complete as we are now [actively moving to Vite](https://github.com/PhilanthropyDataCommons/front-end/issues/720).
