### ISSUE TITLE
Customize dependabot frequency and severity

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#591]
We get a lot of dependabot PRs. A lot. Most of them are non-urgent type updates, but even some of our functional libraries are seemingly constantly releasing.

In my opinion, there is limited benefit to being notified this frequently to non-urgent notices. Is it possible to reduce the frequency to weekly, but also make an exception for high-vulnerability updates?

Particularly but not exclusively, our OIDC auth library is one we'd particularly want to stay atop vulnerability fixes, yet it has automated releases for nearly every commit, [sometimes multiple times a day](https://github.com/AxaFrance/oidc-client/blob/main/CHANGELOG.md).

**Comment by reefdog** [comment]
Well, we can definitely change the cadence to weekly, right? The "…but faster for high-vulnerability" was a nice-to-have.

Although if we're too worried about missing high-vuln updates on a weekly cadence, we can just leave it as-us (and yes, `wontfix`) and I'll just… ignore some of the type updates / dev dependencies until Monday.

**Comment by slifty** [comment]
Ah I misunderstood the issue scope -- yeah let's change it to weekly
