### ISSUE TITLE
Add proposal side panel to organization page

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#613]
When users click on a proposal in the table on the org detail page, we should load it up into a third panel just like the current data providers data:

![Org - Proposal](https://github.com/PhilanthropyDataCommons/front-end/assets/4731/c4929f5d-e3c4-439f-85d2-acba8d154422)

- Populate the panel just like it would be on the full-sized detail page
- X icon closes the panel
- Expand icon is a link to the proposal detail page itself (so, leave the "org" context entirely; literally just a route to `/proposals/1234` or whatever)
- Highlight current proposal in table (in the org panel)

**Comment by reefdog** [comment]
@hminsky2002 I realize one feature is missing here: highlighting the proposal in the table that is currently "open". Can you tackle that as well?

**Comment by hminsky2002** [comment]
> @hminsky2002 I realize one feature is missing here: highlighting the proposal in the table that is currently "open". Can you tackle that as well? (At least provide the hooks for it; I can tweak the styling.)

Thank you for catching this, I'll add it along with the other requested changes!
