### ISSUE TITLE
Change formatting of navbar dropdowns

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#667]
Tinkering with a user menu for #618 and #619, I realized that… sigh… @slifty was right when he said that our navbar dropdowns don't need the "small all caps title" styling that I gave them, and once we have the user menu (where I definitely prefer *not* to have that styling), it looks weird going back and forth.

So let's turn these:
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/f33ec4f2-2475-4dd2-9f39-38ab5e649c0b" alt="Developer menu" width="300">

Into something more like these:
<img src="https://github.com/PhilanthropyDataCommons/front-end/assets/4731/39edad46-cdc4-474f-9ddd-a1d8e987f68c" alt="User menu" width="300">

**Comment by reefdog** [comment]
@slifty That depends how many Gary Hustwit films you've seen.

**Comment by slifty** [comment]
Gary whosiwhustwit?
