### ISSUE TITLE
Eject React Scripts

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/front-end#692]
Related to Issue #498 

While we are still exploring migrating our development environment to something like vite, we have decided that, regardless, we want to get rid of the react-scripts package.

**Comment by reefdog** [comment]
IMO we can put this on hold until Phase 3 or a rainy day. (Not a priority for this week.)

**Comment by slifty** [comment]
We decided to instead just "Move to Vite": #720
