### ISSUE TITLE
Get the user's ID for use in dependent API calls

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#702]
Several of our issues (#697, #622) require the front-end to know the currently-logged-in-user's ID. Not their Keycloak authentication ID, but their actual ID in the PDC which gets passed in to various calls as the `createdBy` param.

(The API may in the future accept our authentication ID — that is, the `sub` value from our JWT token — in lieu of this, but for now we'll need to know the actual numeric ID.)

Once https://github.com/PhilanthropyDataCommons/service/pull/946 is merged in, we (the front end) can get this from `/users?authenticationId={sub}`, where the value of `sub` is available from within a component as:

```js
const { oidcUser } = useOidcUser();
// Sub now vailable in `oidcUser.sub`
```

We don't want to have to fetch this every time we need it for an API call, so what we should do is either:

1. Fetch and cache it during login: this could turn into a yak shave since we need to insert ourselves into [our OIDC client library](https://github.com/AxaFrance/oidc-client)'s `login()` and `logout()` methods somehow.
2. Fetch and cache it the first time we need it: this may be easier since we control the entire mechanism for, well, when we call the API.

In either case we should be sure to remove it during logout.

_This smells like opening ourselves up to a security or cache-invalidation Problem so I do hope the API lets us pass in the `{sub}` soon (🤞 @slifty since you have nothing else to do right?)._

**Comment by slifty** [comment]
@reefdog another approach for your consideration would be loading the user ID every time before the specific calls that are going to need it.  That way you avoid the cache invalidation issue (though I don't think sub changes for a given user?  So I'm not sure that will ever be an issue.  If sub ever changes then that's actually a huge deal because our current use of it was assuming it was 1:1 to a given account)

FWIW I don't think there are any security issues -- if the sub doesn't match the current user's auth context then it won't expose any actual data (createdBy is just a filter, the narrow result set from a given auth context is driven by the JWT)

**Comment by reefdog** [comment]
@slifty I'd prefer _not_ to make a dependent API call before every call that requires it, if we can help it. (Thus my saying "We don't want to have to fetch this every time we need it for an API call.") It may be the least bad option, but it does have a complexity and performance cost.

I'm a little confused by your parenthetical about changing subs. I know the sub doesn't change; I was talking about caching the user ID in session storage after we fetch it the first time, so we aren't hitting `/users` to get it each time we need it.

My code smell comment — which was about caching the user ID btw — was a little fantastic. I don't actually _know_ what the risks would be. But to phrase it better: caching the user ID in session storage means we basically have a parallel (and ersatz) form of user identification operating alongside our stable and tested user authentication. It has roughly the same needs: init during login, delete at logout, eventually timeout. It feels a little shortsighted for us (on the front end) to start building out this parallel system.

Which is all to say: I don't like preflighting every API call with a hit to `/users` to get the user ID. But I also think caching the user ID has a vague code smell to it.

I guess I've come around to preflighting. 🫠 But I really do wish every call that took a `createdBy={userId}` also took a `createdBySub={sub}` (or whatever you'd call it). That's a weird API design but it certainly would solve my problem. Which I guess is the problem of any system with the authentication system decoupled from the user system.

**Comment by slifty** [comment]
I think this is now resolved since the API endpoint now accepts `createdBy=me`

**Comment by hminsky2002** [comment]
> I think this is now resolved since the API endpoint now accepts `createdBy=me`

Yes I think this is correct! Thank you @slifty
