### ISSUE TITLE
Use types from SDK when available

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/front-end#705]
The PDC SDK provides some of the types that we're manually defining, e.g. our [`ApiProposal`](https://github.com/PhilanthropyDataCommons/front-end/blob/3a3ca478660406aedc416ed183ef2317f555627a/src/pdc-api.ts#L181-L193). These are brittle and in some cases already out of date.

We should rely on the SDK for these, now that we can!

**Comment by reefdog** [comment]
@hminsky2002 I went ahead and got started on this because I realized so much of our queued work requires knowledge of the latest types, and it makes more sense to use the SDK than update our local stand-ins. But I haven't finished yet; if you end up being blocked by this, feel free to pick up the branch (`705-use-sdk-for-interfaces`) and finish it up.

**Comment by slifty** [comment]
@reefdog I should probably bump the SDK version so you have the `Users` type.

**Comment by slifty** [comment]
New SDK version is released!
