### ISSUE TITLE
Remove initial value for BulkUploadListItem reducer function

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/front-end#803]
The reducer function in the BulkUploadListItem component defaults to the null value: 

```typescript
const metadataElements = metadata
		.filter((datum) => datum !== null)
		.reduce(
			(accumulator, datum) =>
				accumulator === null ? (
					datum
				) : (
					<>
						{accumulator}
						{METADATA_DELIMITER}
						{datum}
					</>
				),
			null,
		);
```
During the work on #748, we discovered that the value defaulting to null throws a type error on update of our typescript eslint plugin. 
As pointed out by @jasonaowen in https://github.com/PhilanthropyDataCommons/front-end/pull/748#discussion_r1710319764, the best way to handle this is to remove the initial value entirely, as well as the trigraph operator

**Comment by reefdog** [comment]
Whoops, the intention of the original code here was to _not_ generate delimiters unless there were things to delimit. With the new code, a set of just one value will always be prefixed with a delimiter.

Maybe there's a better way to accomplish this, but basically:

1. ✅ `["foo"]` → `"foo"`
2. ✅ `["foo", "bar"]` → `"foo • bar"`
3. ❌ `["foo"]` → `"• foo"`

Can you verify that the new code won't end up generating situation ③?

**Comment by jasonaowen** [comment]
@reefdog I believe this should be purely a refactor, and have no change in behavior, and I seem to have tested it at the time: https://github.com/PhilanthropyDataCommons/front-end/pull/804#pullrequestreview-2264149046 . See that PR for more details, but the key insight is that JavaScript will automatically handle a missing base case:

> The first time that the callback is run there is no "return value of the previous calculation". If supplied, an initial value may be used in its place. Otherwise the array element at index 0 is used as the initial value and iteration starts from the next element (index 1 instead of index 0).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

**Comment by reefdog** [comment]
@jasonaowen I don't see how it can have the same behavior. Now it's always returning this string template:

```jsx
<>
	{accumulator}
	{METADATA_DELIMITER}
	{datum}
</>
```

How does the new version know to omit `{METADATA_DELIMITER}` when this is the first iteration? (It doesn't matter whether it omits `{accumulator}` or not, because to your point, when it's `null` it won't output anything anyway.)

**Comment by reefdog** [comment]
@jasonaowen Wait… now I'm wondering why I don't just `join`. Clearly that's what I'm doing here, and I'm sure there's a good reason… :squint: but evidently I didn't document that reason.

**Comment by reefdog** [comment]
@jasonaowen Oh my gosh Jason, I finally get it. 🤦 Thank you for indulging me! Disregard, and thank you (both?) for catching/changing this.

**Comment by slifty** [comment]
Hey guys I just wanted to comment so I could feel like I'm part of the group.
