### ISSUE TITLE
new user not rendering any records 

### ISSUE THREAD

**Issue by jmergy** [PhilanthropyDataCommons/front-end#867]
Been a while on new user creation for PDC but noticing all parameters set on the user but I am not seeing any records currently. UI is showing "Loading..." with no records on Organizations or Proposals. 

![image](https://github.com/user-attachments/assets/bb8871cb-bb19-4ca2-99e5-9589565041fa)

**Comment by jmergy** [comment]
@slifty @kfogel okay - if just the front-end is problematic right now, as long as the records will render in the API, that should be okay. I can test. I just am setting up new users and want to be sure they work prior to engaging the new users and I just testing via the front-end. I can test via swagger or Postman too.

**Comment by jmergy** [comment]
via swagger getting a perm denied for table users error. We have not created new users in a while so just trying to figure this out but I know work is also going on here too. @slifty @bickelj @kfogel 
![image](https://github.com/user-attachments/assets/5f3fe26d-33d0-439d-b305-46b888c7fbf8)

**Comment by slifty** [comment]
@jmergy I am betting this is related to the change to the app structure that @jasonaowen just launched.

**Comment by jmergy** [comment]
Thanks @slifty and @jasonaowen - elevating the need for the changes now.

**Comment by jmergy** [comment]
testing again with a new keycloak user in the pdc and looks like I can start to get data from the API again and starting to see the updated endpoints 
![image](https://github.com/user-attachments/assets/751c0022-dcdd-4d48-aa30-4240b12be8b9)
