### ISSUE TITLE
Resolve current front-end functionality with service changes

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/front-end#869]
As per a discussion with @kfogel, while we don't want to be actively developing the front-end we'd like to ensure that it remains functional as we develop the service. This issue encompasses those necessary changes to the front-end. 

- [ ] Make the bulk-upload page accept new bulk uploads
- [x] #870

**Comment by slifty** [comment]
To be clear regarding the reason for closing: this was functionalyl a duplicate of #836
