### ISSUE TITLE
Refactor Organizations to Changemaker

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/front-end#870]

**Comment by slifty** [comment]
@hminsky2002 you might consider having a general issue for updating to the latest SDK which I think will capture all of the various changes you need to make in one swoop.

**Comment by hminsky2002** [comment]
@slifty I've never seen a comment posted in realtime on github. cool. Yeah I think you're right, but I figured it would be better to split it into two because this refactor is really big! I guess I could just split it into two commits?

**Comment by hminsky2002** [comment]
@slifty it seems like issue #836 already exists, so I'll just refer to that one moving forward!
